### ISSUE TITLE
Canny control for the material editing

### ISSUE THREAD

**Issue by Hsintien-Ng** [ttchengab/zest_code#1]
Hi, it's a great work.
What about using canny controlnet for inpainting instead of depth controlnet?
Does canny guidance conflict with material editing?
thanks~

**Comment by ttchengab** [comment]
Hi, thanks for your kind words!

We choose depth map because the geometry helps overwrite the geometry of the material exemplar. The code would still work if you change from depth controlnet to canny controlnet, but I suspect it wouldn't perform as nicely. In addition, the patterns on the canny map could also interfere with the textural patterns from the material exemplar.
