### ISSUE TITLE
Initial Image Strength = 0.9999?

### ISSUE THREAD

**Issue by CesarERamosMedina** [ttchengab/zest_code#5]
If the initial image strength is 1 (or close to 1), my understanding is that this essentially ignores the masked portion of the initial image in the diffusion process. I believe that the default value for strength on the SDXL Inpaint Pipeline (used on the demo) has a strength of [0.9999](https://github.com/huggingface/diffusers/blob/9d50f7eec1ed9bf3581210efe05a57229733c3fb/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py#L1139). Why does the grayed-out area still impact the image generated?

**Comment by ttchengab** [comment]
Hi @CesarERamosMedina, I think this might be an issue within diffuser itself. I did a test on the demo_gradio.py just to confirm: If you swap out the L140 init_img = grayscale_init_img with init_img = input_image.resize((1024,1024)) (without foreground decoloring), you will realize that the pumpkin preserves a lot of its original color like the following:
<img width="768" alt="Screenshot 2024-04-16 at 22 03 56" src="https://github.com/ttchengab/zest_code/assets/22548004/a0ea8eb2-e1e1-43b6-8236-779ee0dbc703">

whereas using the original code gives us this:
<img width="757" alt="Screenshot 2024-04-16 at 22 09 55" src="https://github.com/ttchengab/zest_code/assets/22548004/9e9e731d-6133-499e-bb05-cb088783f595">

We also do realize in our experiment mentioned in the paper that using completely noise to start with would give less hints about the illumination.

**Comment by CesarERamosMedina** [comment]
Yeah I remember seeing this in the paper (as well as the comparison when just doing random noise), but I was unsure on why this was the case since I'm not sure how much "information" the grayed out image contains. Thank you so much for the reply!

**Comment by CesarERamosMedina** [comment]
Oh, and really cool results!

**Comment by CesarERamosMedina** [comment]
One quick hypothesis:
int(30 steps * 0.9999) = 29 steps, so it seems that a bit of information might still be going through from the original image. Results would possibly differ with a strength being exactly 1.0

**Comment by ttchengab** [comment]
Hi @CesarERamosMedina. You are right, that is one of the reasonings. If you set it to 1, the base color prior does decrease a lot. However, I do still notice a little bit of pumpkin orange:

<img width="755" alt="Screenshot 2024-04-16 at 22 55 58" src="https://github.com/ttchengab/zest_code/assets/22548004/b8c52897-75dd-4f08-99e3-e0817d417912">

The shading on the object also becomes less apparent.

Anyways, thanks for the insight!

**Comment by CesarERamosMedina** [comment]
On the contrary, thank you so much for checking!

**Comment by wonjunior** [comment]
I was also wondering about this for some time, the reason there is some information leakage is because - as you said  
[CesarERamosMedina](https://github.com/CesarERamosMedina) - `strength`  is by default set to `0.9999`  in `StableDiffusionXLControlNetInpaintPipeline`. This is by the way different from `StableDiffusionInpaintPipeline` which sets it to `1.0` by default... So of course there is still a small amount of the latent code used to initialize the noisy latent, but the main reason lies in [this line](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py#L943):

```
latents = noise if is_strength_max else self.scheduler.add_noise(image_latents, noise, timestep)
```

Where `is_strength_max` is set to `strength == 1` in the `__call__`  function. So in fact when `strength` is `0.9999` , it uses a very noisy latent, while when strength is set to ` 1.0`, it yields **pure noise** (thus no information leakage). 

That was maybe an aspect that was overlooked!
